version: "3"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
#      - mongo
#      - postgres
      - rabbitmq
    command: rabbitmq:5672

  api:
    image: farit2000/fandncloud.api
    restart: on-failure
    links:
      - rabbitmq
    ports:
      - "5000:5000"

  activities-service:
    image: farit2000/fandncloud.services.basketactivities
    restart: on-failure
    links:
      - rabbitmq
#      - mongo
    ports:
      - "5050:5050"

  identity-service:
    image: farit2000/fandncloud.services.identity
    restart: on-failure
    links:
      - rabbitmq
#      - postgres
    ports:
      - "5100:5100"

#  mongo:
#    image: mongo
#    volumes:
#      - ./data/db:/data/db
#    ports:
#      - "27017:27017"

#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: fandncloud
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 081569
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"